src/Temp.java

Hey @Muiqqq please review this awesome feature.

Initialize Temp.java.

---

src/Math.java
src/Temp.java

Hey @Muiqqq please review this important new class.

Math class

---

src/Temp.java

Hey @Muiqqq please review this important new feature.
Yours truly,

Add print(param) method to Temp.java.

---

src/Temp.java

Hey @Muiqqq please review these important features.
printDyslexicHello method finally added as customer wanted it.

Hello Features

---

src/Hello.java

Hey @Muiqqq please review this important new feature to Hello.class

Hello feature 2

---

src/Hello.java

Hey @Muiqqq please review these important features.
>

Hello feature3

---

src/Hello.java

Hey @Muiqqq please review this important feature. 
Your obedient servant, Ikuinen Padawan

Hello feature4

---

src/muikku.app/Calculator.java
src/muikku.app/Main.java
src/muikku.app/MathUtils.java
src/muikku.app/Util.java

Take a look at this nifty calculator!

Calculator initial

---

src/muikku.app/Calculator.java
src/muikku.app/readme.txt

Documentation for Calculator.java

Calculator doc

---

src/Hello.java

Hey @Muiqqq please review this important feature.

Matter feature

---

src/muikku.app/Calculator.java
src/muikku.app/readme.txt

Calculator stuff

---

src/muikku.app/MathUtils.java

Math utils doc

---

src/Hello.java

Hey @Muiqqq please review this important bug fix to release 1.0 branch.

Change every word's first letter after "Hello" to uppercase.

---

src/Hello.java

Hey @Muiqqq please review this important feature.

Hello feature5

---

src/muikku.app/MathUtils.java

Mathutils doc

---

src/muikku.app/Calculator.java

bugfixes from release branch to devel

---

src/Hello.java

Hey @Muiqqq please review this important feature.

Language support

---

src/muikku.app/MathQuiz.java
src/muikku.app/readme-mathquiz.txt

Mathquiz app

---

src/Hello.java

Hey @Muiqqq please review this important fix.

Language support fix

---

src/Hello.java

Hey @Muiqqq please review this important fix.

Fix some problem.

---

src/Game/Game.java

Quickfixes

---

src/Game/Game.java

More fixes
